language: ruby
rvm:
  # Current ruby stable version
  - 3.0
  # Ubuntu 20.10
  - 2.7
  # Ubuntu 19.10
  - 2.5
  # Mac v11 Big Sur
  # - 2.6?
  # Mac v10.15 Catalina
  - 2.6
  # Mac v10.14 Mojave
  - 2.3.7
script: "bundle exec rake"
before_install:
  - sudo apt-get -y install ledger hledger
  - gem install -v 1.17.3 bundler
